# Generated by Django 5.2.4 on 2025-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Mark true if this is a correct answer'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(help_text='Enter the option text', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Enter the quiz question text'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Enter the name of the role (e.g., Data Scientist)', max_length=100, unique=True),
        ),
    ]
